# Generated by Django 4.2.4 on 2023-08-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Well',
            new_name='Course',
        ),
    ]
